# -*- coding: utf-8 -*-
"""Task One - Day Two (Serendipity Book Club)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MeNfMJJxjtUvtW0bartpusTBy0EFB9AK
"""

# Prompt user to enter the number of books
number_of_books = int(input("Welcome to Serendipity Booksellers Book Club.\
Please enter the number of books you have purchased this month: "))
message = ""

if number_of_books < 0:
    message = "Please enter a positive number."
              
else:
    message = "You have been awarded "

    if number_of_books == 0:
        message += "0 "
    elif number_of_books == 1:
        message += "6 "
    elif number_of_books == 2:
        message += "16 "
    elif number_of_books == 3:
        message += "32 "
    elif number_of_books >= 4:
        message += "60 "

    message += "points for your purchase. Happy Reading."

print(message)